# see more about dockerfile templates here: https://www.balena.io/docs/learn/develop/dockerfile/#dockerfile-templates
# and about balena base images here: https://www.balena.io/docs/reference/base-images/base-images/
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-python:3.6.10-3.11-build-20200405 as build
# Defines our working directory in container
WORKDIR /usr/src/app

RUN apk add \
    libjpeg-turbo \
    openjpeg \
    tiff \
    libxcb \    
    openblas-dev \
    freetype-dev \
    python3-dev

RUN python3 -m venv /usr/src/app/venv
ENV PATH="/usr/src/app/venv/bin:$PATH"
# bunch of flask ask stuff 
RUN pip3 install  \
    inky RPi.GPIO Pillow font_fredoka_one

# # download display.py to run Inky pHAT
RUN wget -q https://raw.githubusercontent.com/himalayanelixir/pi-inky-phat/master/display.py
COPY motor_control.py ./

# ########################
# ########################

# # new image
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-python:3.6.10-3.11-run-20200405 as run
WORKDIR /usr/src/app
RUN apk add \
    libjpeg-turbo \
    openjpeg \
    tiff \
    libxcb \    
    openblas-dev \
    freetype-dev
ENV PATH="/usr/src/app/venv/bin:$PATH"
COPY --from=build /usr/src/app /usr/src/app
# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

# server.js will run when container starts up on the device
# CMD [". /usr/src/app/env/bin/python3", "main.py"]
CMD ["bash"]